//
// Test Bench Module Ori_Alon_Lab_1_lib.apb_slave_module_tester.apb_slave_module_tester
//
// Created:
//          by - vain.UNKNOWN (TOMER)
//          at - 12:07:10 01/30/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module apb_slave_module_tester (clk_i,
                                rst_ni,
                                psel_i,
                                penable_i,
                                pwrite_i,
                                pstrb_i,
                                pwdata_i,
                                paddr_i,
                                pready_o,
                                pslverr_o,
                                prdata_o,
                                busy_o
                               );

// Local declarations

parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
parameter ADDR_WIDTH = 32;
parameter MAX_DIM = (BUS_WIDTH / DATA_WIDTH);
parameter IDLE_S = 2'b00;
parameter ACCESS_READ = 2'b01;
parameter ACCESS_WRITE = 2'b10;


output clk_i;
output rst_ni;
output psel_i;
output penable_i;
output pwrite_i;
output pstrb_i;
output pwdata_i;
output paddr_i;
input  pready_o;
input  pslverr_o;
input  prdata_o;
input  busy_o;

wire clk_i;
wire rst_ni;
wire psel_i;
wire penable_i;
wire pwrite_i;
wire pstrb_i;
wire pwdata_i;
wire paddr_i;
wire pready_o;
wire pslverr_o;
wire prdata_o;
wire busy_o;


endmodule // apb_slave_module_tester


