//
// Test Bench Module Ori_Alon_Lab_1_lib.memory_modul_tb.memory_modul_tester
//
// Created:
//          by - vain.UNKNOWN (TOMER)
//          at - 21:53:07 02/ 4/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module memory_modul_tb;

// Local declarations
parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
parameter ADDR_WIDTH = 32;
localparam MAX_DIM = (BUS_WIDTH / DATA_WIDTH);
parameter SPN = 4;
localparam BYTE = 8;

// Internal signal declarations
wire clk_i;
wire [ADDR_WIDTH-1:0] addr_i;
wire [DATA_WIDTH-1:0] data_i;
wire pwrite_i;
wire [DATA_WIDTH-1:0] data_o;

memory_modul #(32,64,32,4) U_0(
   .clk_i    (clk_i),
   .addr_i   (addr_i),
   .data_i   (data_i),
   .pwrite_i (pwrite_i),
   .data_o   (data_o)
);

memory_modul_tester #(32,64,32,4) U_1(
   .clk_i    (clk_i),
   .addr_i   (addr_i),
   .data_i   (data_i),
   .pwrite_i (pwrite_i),
   .data_o   (data_o)
);

endmodule // memory_modul_tb


