//
// Test Bench Module Ori_Alon_Lab_1_lib.memory_modul_tester.memory_modul_tester
//
// Created:
//          by - vain.UNKNOWN (TOMER)
//          at - 18:19:01 02/ 4/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module memory_modul_tester (clk_i,
                            addr_i,
                            data_i,
                            pwrite_i,
                            data_o
                           );

// Local declarations

parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
parameter ADDR_WIDTH = 32;
localparam  MAX_DIM = (BUS_WIDTH / DATA_WIDTH);
parameter SPN = 4;
localparam BYTE = 8;


output clk_i;
output addr_i;
output data_i;
output pwrite_i;
input  data_o;

reg clk_i;
reg [ADDR_WIDTH-1:0] addr_i;
reg [DATA_WIDTH-1:0] data_i;
reg pwrite_i;
wire[DATA_WIDTH-1:0] data_o;

initial begin: setup_clk
  clk_i = 1'b0;
  forever #1 clk_i = ~clk_i;
end

task do_write;
  input [ADDR_WIDTH-1:0] addr_write;
  input [DATA_WIDTH-1:0] data_write;
    begin
      addr_i = addr_write;
      data_i = data_write;
      pwrite_i = 1'b0;
      #1;
      pwrite_i = 1'b1;
      #2;
      pwrite_i = 1'b0;
    end
endtask
    
task do_read;
    begin
      do_write(1,1); //insert some numbers to some addressess
      do_write(2,12);
      do_write(3,23);
      #5;
      addr_i = 1; //need to see 1 in data_o
      #1;
      addr_i = 2; //need to see 12 in data_o
      #1;
      addr_i = 3; //need to see 23 in data_o
    end
endtask    
    
    
initial begin
    do_write(5,10);
    #1;
    do_read;
end   
    
    
endmodule // memory_modul_tester


