//
// Test Bench Module Ori_Alon_Lab_1_lib.operands_module_tester.operands_module_tester
//
// Created:
//          by - orisad.UNKNOWN (TOMER)
//          at - 15:31:14 02/ 2/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module operands_module_tester (clk_i,
                               rst_ni,
                               write_enable_i,
                               address_i,
                               write_data_i,
                               read_data_o
                              );

// Local declarations

parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
parameter ADDR_WIDTH = 32;
parameter MAX_DIM = (BUS_WIDTH / DATA_WIDTH);


output clk_i;
output rst_ni;
output write_enable_i;
output address_i;
output write_data_i;
input  read_data_o;

wire clk_i;
wire rst_ni;
wire write_enable_i;
wire address_i;
wire write_data_i;
wire read_data_o;


endmodule // operands_module_tester


